language: python
cache: pip

# Matrix of build options
python:
  - '3.5'
  - '3.6'
  - '3.7'

node_js:
 - 'node'

env:
  global:
    - DJANGO_SETTINGS_MODULE="tests.app.settings"
    - TOX_ENV=
  matrix:
    - DJANGO='20' WAGTAIL='27'
    - DJANGO='21' WAGTAIL='27'
    - DJANGO='22' WAGTAIL='27'

install:
  - pip install --upgrade pip wheel tox

cache:
  pip: true
  directories:
    - node_modules


script:
  # Run tox using either a specific environment from TOX_ENV,
  # or building one from the environment variables
  - tox -e "${TOX_ENV:-py${TRAVIS_PYTHON_VERSION/./}-dj${DJANGO}-wt${WAGTAIL}}"
