language: python
cache: pip

# Matrix of build options
python:
  - '2.7'
  - '3.4'
  - '3.5'

node_js:
 - 'node'

env:
  global:
    - DJANGO_SETTINGS_MODULE="tests.app.settings"
    - TOX_ENV=
  matrix:
    - DJANGO='19' WAGTAIL='15'
    - DJANGO='110' WAGTAIL='15'
    - DJANGO='19' WAGTAIL='16'
    - DJANGO='110' WAGTAIL='16'
    - DJANGO='19' WAGTAIL='17'
    - DJANGO='110' WAGTAIL='17'

install:
  - pip install --upgrade pip wheel tox

cache:
  pip: true
  directories:
    - node_modules


script:
  # Run tox using either a specific environment from TOX_ENV,
  # or building one from the environment variables
  - tox -e "${TOX_ENV:-py${TRAVIS_PYTHON_VERSION/./}-dj${DJANGO}-wt${WAGTAIL}}"
